version: '2'
services:
  postgres-db:
    container_name: postgresdb
    image: library/postgres:13.5-alpine
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=gureli
      - POSTGRES_PASSWORD=gureli
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ersin@gureli.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  currency-exchange-service:
    container_name: currency-exchange-service
    image: currency-exchange
    depends_on:
      - postgres-db
    ports:
      - "8091:8091"
    environment:
      -SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/postgres
      -SPRING_DATASOURCE_USERNAME: gureli
      -SPRING_DATASOURCE_PASSWORD: gureli

volumes:
  local_pgdata:
  pgadmin-data: